/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homecredit;

import homecredit.controllers.Consultas;
import homecredit.dbConnection.Conn;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author garroakion
 */
public class Interface extends javax.swing.JFrame {
    
    protected Conn connect = null;

    /**
     * Creates new form Inter
     */
    public Interface() {
        initComponents();
        ConecctSQL();
        disableAllComponents();
    }
    
    private void disableAllComponents() {
        changeStateHomePanel(false);
        changeStateLoansPanel(false);
        changeStateBalancePanel(false);
        changeStatePeoplePanel(false);
        changeStateHome2Panel(false);
        
    }
    
    private void changeStateHomePanel(Boolean flag) {
        this.homePanel.setVisible(flag);
        this.homePanel.setEnabled(flag);
    }
    
    private void changeStateLoansPanel(Boolean flag) {
        this.loansPanel.setVisible(flag);
        this.loansPanel.setEnabled(flag);
    }
    
    private void changeStateBalancePanel(Boolean flag) {
        this.balancePanel.setVisible(flag);
        this.balancePanel.setEnabled(flag);
        
    }
    
    private void changeStatePeoplePanel(Boolean flag) {
        
        this.cardsPanel.setVisible(flag);
        this.cardsPanel.setEnabled(flag);
    }
    
    private void changeStateHome2Panel(Boolean flag) {
        
        this.homePanel2.setVisible(flag);
        this.homePanel2.setEnabled(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        cardsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idPeople = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        creditCardList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        cantidaRegistros = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loansPanel = new javax.swing.JPanel();
        cantidaRegistrosLoans = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loansList = new javax.swing.JList<>();
        searchLoans = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        comboIncomeType = new javax.swing.JComboBox<>();
        comboContract = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboIncomeTotal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelTx = new javax.swing.JLabel();
        homePanel2 = new javax.swing.JPanel();
        balancePanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        dashLabel = new javax.swing.JLabel();
        loansLabel = new javax.swing.JLabel();
        cardsLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeCreditDashBoard");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        setState(60);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardsPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardsPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        cardsPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        cardsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        cardsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Credit Card Balance");
        cardsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad Registros:");
        cardsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, 30));

        idPeople.setBackground(new java.awt.Color(255, 255, 255));
        idPeople.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        idPeople.setForeground(new java.awt.Color(0, 0, 0));
        idPeople.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardsPanel.add(idPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 455, 180, 30));

        creditCardList.setBackground(new java.awt.Color(255, 255, 255));
        creditCardList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        creditCardList.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        creditCardList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(creditCardList);

        cardsPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 650, 410));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Search Balance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        cardsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 130, 40));

        cantidaRegistros.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cantidaRegistros.setForeground(new java.awt.Color(0, 0, 0));
        cardsPanel.add(cantidaRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 90, 30));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ID:");
        cardsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 30, 30));

        getContentPane().add(cardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 600));

        loansPanel.setBackground(new java.awt.Color(255, 255, 255));
        loansPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        loansPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        loansPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        loansPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cantidaRegistrosLoans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cantidaRegistrosLoans.setForeground(new java.awt.Color(0, 0, 0));
        loansPanel.add(cantidaRegistrosLoans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 140, 30));

        jScrollPane1.setBorder(null);

        loansList.setBackground(new java.awt.Color(255, 255, 255));
        loansList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loansList.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        loansList.setForeground(new java.awt.Color(0, 0, 0));
        loansList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(loansList);

        loansPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 660, 350));

        searchLoans.setText("Search Loans");
        searchLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLoansActionPerformed(evt);
            }
        });
        loansPanel.add(searchLoans, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Income Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 100, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contract type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Income type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, 30));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Closed" }));
        jPanel1.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 30));

        comboIncomeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Working", "Commercial associate", "State servant", "Pensioner" }));
        jPanel1.add(comboIncomeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        comboContract.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash loans", "Revolving loans" }));
        jPanel1.add(comboContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Credit Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 100, 30));

        comboIncomeTotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50000", "100000", "150000", "200000 ", "250000", "300000", "500000" }));
        jPanel1.add(comboIncomeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 30));

        loansPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 660, 90));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filtros de busqueda:");
        loansPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 30));

        labelTx.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTx.setForeground(new java.awt.Color(0, 0, 0));
        labelTx.setText("Cantidad de registros:");
        loansPanel.add(labelTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 180, 30));

        getContentPane().add(loansPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 600));

        homePanel2.setBackground(new java.awt.Color(255, 255, 255));
        homePanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        homePanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        homePanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        homePanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(homePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 600));

        balancePanel.setBackground(new java.awt.Color(255, 255, 255));
        balancePanel.setMaximumSize(new java.awt.Dimension(800, 600));
        balancePanel.setMinimumSize(new java.awt.Dimension(800, 600));
        balancePanel.setPreferredSize(new java.awt.Dimension(800, 600));
        balancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(balancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 600));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setMaximumSize(new java.awt.Dimension(800, 600));
        homePanel.setMinimumSize(new java.awt.Dimension(800, 600));
        homePanel.setPreferredSize(new java.awt.Dimension(800, 600));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 690, 600));

        menuPanel.setBackground(new java.awt.Color(0, 82, 248));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        dashLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashLabel.setText("DashBoard");
        menuPanel.add(dashLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        loansLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        loansLabel.setForeground(new java.awt.Color(255, 255, 255));
        loansLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loansLabel.setText("Loans");
        loansLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loansLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loansLabelMouseClicked(evt);
            }
        });
        menuPanel.add(loansLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, 30));

        cardsLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cardsLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardsLabel.setText("Cards");
        cardsLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cardsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardsLabelMouseClicked(evt);
            }
        });
        menuPanel.add(cardsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, 30));

        balanceLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balanceLabel.setText("Balances");
        balanceLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        balanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceLabelMouseClicked(evt);
            }
        });
        menuPanel.add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 30));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loansLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loansLabelMouseClicked
        disableAllComponents();
        changeStateLoansPanel(true);
    }//GEN-LAST:event_loansLabelMouseClicked

    private void cardsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardsLabelMouseClicked
        disableAllComponents();
        this.changeStatePeoplePanel(true);
    }//GEN-LAST:event_cardsLabelMouseClicked

    private void balanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceLabelMouseClicked
        disableAllComponents();
        this.changeStateBalancePanel(true);
    }//GEN-LAST:event_balanceLabelMouseClicked

    private void searchLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLoansActionPerformed
        
        String incomeType = this.comboIncomeType.getSelectedItem().toString();
        String Active = this.comboStatus.getSelectedItem().toString();
        String ContractType = this.comboContract.getSelectedItem().toString();
        String total = this.comboIncomeTotal.getSelectedItem().toString();
        
        CallableStatement cstmt = null;
        ResultSet rs = null;
        try {
            cstmt = connect.obtainConnection().prepareCall(
                    "{call dbo.SPGetAllLoansWithParamethers(?,?,?,?)}",
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            
            cstmt.setString("inputIncome", incomeType);
            cstmt.setString("inputActive", Active);
            cstmt.setString("inputContract", ContractType);
            cstmt.setString("inputTotal", total);
            
            cstmt.execute();
            rs = cstmt.getResultSet();
            
            DefaultListModel model = new DefaultListModel();
            this.loansList.setModel(model);
            int i=0;
            while (rs.next()) {
                i++;
                String value
                        = "ID: " + rs.getInt("SK_ID_CURR") + "    "
                        + "Contract Type: " + rs.getString("NAME_CONTRACT_TYPE") + "    "
                        + "Income: " + rs.getString("AMT_INCOME_TOTAL") + "    "
                        + "Income Type: " + rs.getString("NAME_INCOME_TYPE") + "    "
                        + "Credit Active: " + rs.getString("CREDIT_ACTIVE") + "    "
                        + "Months Balance: " + rs.getString("MONTHS_BALANCE");
                model.addElement(value);
                
            }
            this.cantidaRegistrosLoans.setText(""+i);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        } finally {
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) {
                    System.out.println(ex.toString());
                }
            }
        }
        if (cstmt != null) {
            try {
                cstmt.close();
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
            
        }
        

    }//GEN-LAST:event_searchLoansActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = this.idPeople.getText();
        if (!id.equals("")) {
            CallableStatement cstmt = null;
            ResultSet rs = null;
            try {
                cstmt = connect.obtainConnection().prepareCall(
                        "{call dbo.SPGetCredidCardDetails(?)}",
                        ResultSet.TYPE_SCROLL_INSENSITIVE,
                        ResultSet.CONCUR_READ_ONLY);
                
                cstmt.setString("inputID", id);
                
                cstmt.execute();
                rs = cstmt.getResultSet();
                
                DefaultListModel model = new DefaultListModel();
                this.creditCardList.setModel(model);
                
                int i = 0;
                while (rs.next()) {
                    i++;
                    String value
                            = "ID: " + rs.getInt("SK_ID_CURR") + "    "
                            + "Code Gender: " + rs.getString("CODE_GENDER") + "    "
                            + "Months Balance: " + rs.getString("MONTHS_BALANCE") + "    "
                            + "Balance: " + rs.getString("BALANCE") + "    "
                            + "Credit Limit: " + rs.getString("CREDIT_LIMIT_ACTUAL") + "    ";
                    model.addElement(value);
                    
                }
                this.cantidaRegistros.setText("" + i);
                
            } catch (Exception ex) {
                System.out.println(ex.toString());
            } finally {
                if (rs != null) {
                    try {
                        rs.close();
                    } catch (SQLException ex) {
                        System.out.println(ex.toString());
                    }
                }
            }
            if (cstmt != null) {
                try {
                    cstmt.close();
                } catch (SQLException ex) {
                    System.out.println(ex.toString());
                }
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite un id");
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void ConecctSQL() {
        this.connect = new Conn();
        System.out.println("Inicio correcto");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel balancePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cantidaRegistros;
    private javax.swing.JLabel cantidaRegistrosLoans;
    private javax.swing.JLabel cardsLabel;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JComboBox<String> comboContract;
    private javax.swing.JComboBox<String> comboIncomeTotal;
    private javax.swing.JComboBox<String> comboIncomeType;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JList<String> creditCardList;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homePanel2;
    private javax.swing.JTextField idPeople;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTx;
    private javax.swing.JLabel loansLabel;
    private javax.swing.JList<String> loansList;
    private javax.swing.JPanel loansPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton searchLoans;
    // End of variables declaration//GEN-END:variables
}
