
CREATE SCHEMA Creditos;
CREATE SCHEMA Saldos;
CREATE SCHEMA Acceso;

ALTER SCHEMA Creditos TRANSFER OBJECT::dbo.bureau;
ALTER SCHEMA Creditos TRANSFER OBJECT::dbo.AMT_CREDIT;
ALTER SCHEMA Creditos TRANSFER OBJECT::dbo.bureau_balance;

ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.previous_application;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.POS_CASH_balance;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.installments_payments;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.credit_card_balance;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.AMT_BALANCE_DETAILS;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.CNT_BALANCE_DETAILS;
ALTER SCHEMA Saldos TRANSFER OBJECT::dbo.AMT_PREVIOUS_DETAILS;


ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.AddressClientInformation;
ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.AMT_REQ_CREDIT;
ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.application_train;
ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.ClientApartmentsDetails;
ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.FlagDocument;
ALTER SCHEMA Acceso TRANSFER OBJECT::dbo.FlagsProvidedInformation;