USE [ProyectoBasesDatos2]
GO

DROP TABLE [CREDITOS].[AMT_CREDIT];
CREATE TABLE [CREDITOS].[AMT_CREDIT](
	[SK_ID_BUREAU] INT NULL, /*Agregar la FK*/
	[MAX_OVERDUE] INT NULL,
	[SUM] [varchar](50) NULL,
	[SUM_DEBT] [varchar](50) NULL,
	[SUM_LIMIT] [varchar](50) NULL,
	[SUM_OVERDUE] [varchar](50) NULL,
	[ANNUITY] [varchar](50) NULL
) 
ALTER TABLE Creditos.AMT_CREDIT
drop constraint FK_AMT_CREDIT_Bureau;

Delete from Creditos.AMT_CREDIT;

ALTER TABLE Creditos.AMT_CREDIT
   ADD CONSTRAINT FK_AMT_CREDIT_Bureau FOREIGN KEY (SK_ID_BUREAU)
      REFERENCES Creditos.bureau(SK_ID_BUREAU)
;

