USE [ProyectoBasesDatos2]
GO

DROP TABLE [Saldos].[AMT_PREVIOUS_DETAILS];
CREATE TABLE [Saldos].[AMT_PREVIOUS_DETAILS](
	[SK_ID_PREV] INT NULL, /*Agregar FK*/

	[AMT_ANNUITY] [varchar](50) NULL,
	[AMT_APPLICATION] [varchar](50) NULL,
	[AMT_CREDIT] [varchar](50) NULL,
	[AMT_DOWN_PAYMENT] [varchar](50) NULL,
	[AMT_GOODS_PRICE] [varchar](50) NULL,

) 


TRUNCATE TABLE Saldos.AMT_PREVIOUS_DETAILS;
DELETE FROM Saldos.AMT_PREVIOUS_DETAILS;


ALTER TABLE Saldos.AMT_PREVIOUS_DETAILS
DROP CONSTRAINT FK_AMT_PREVIOUS_previousA;

ALTER TABLE Saldos.AMT_PREVIOUS_DETAILS
   ADD CONSTRAINT FK_AMT_PREVIOUS_previousA FOREIGN KEY (SK_ID_PREV)
      REFERENCES Saldos.previous_application(SK_ID_PREV)
;