/*Index Cluster CNT_BALANCE_DETAILS */

CREATE CLUSTERED INDEX [ClusteredIndex-20220611-144353] ON [Saldos].[CNT_BALANCE_DETAILS]
(
	[ID_CCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO


/*Index Cluster AMT_PREVIOUS_DETAILS */

CREATE CLUSTERED INDEX [ClusteredIndex-20220611-144629] ON [Saldos].[AMT_PREVIOUS_DETAILS]
(
	[SK_ID_PREV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)




/*Index Cluster AMT_BALANCE_DETAILS*/


CREATE CLUSTERED INDEX [ClusteredIndex-20220611-144758] ON [Saldos].[AMT_BALANCE_DETAILS]
(
	[ID_CCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*Index Cluster bureau_balance*/
CREATE CLUSTERED INDEX [ClusteredIndex-20220611-145026] ON [Creditos].[bureau_balance]
(
	[SK_ID_BUREAU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]



/*Index Cluster AMT_CREDIT*/


CREATE CLUSTERED INDEX [ClusteredIndex-20220611-145213] ON [Creditos].[AMT_CREDIT]
(
	[SK_ID_BUREAU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)


/*Index Cluster FlagsProvidedInformation*/

CREATE CLUSTERED INDEX [ClusteredIndex-20220611-151225] ON [Acceso].[FlagsProvidedInformation]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/* Index cluster FlagDocument*/

CREATE CLUSTERED INDEX [ClusteredIndex-20220611-151311] ON [Acceso].[FlagDocument]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)


/*Index Cluster [ClientApartmentsDetails]*/



CREATE CLUSTERED INDEX [ClusteredIndex-20220611-151717] ON [Acceso].[ClientApartmentsDetails]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)


/*Index Cluester AMT_REQ_CREDIT*/

CREATE CLUSTERED INDEX [ClusteredIndex-20220611-152203] ON [Acceso].[AMT_REQ_CREDIT]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)


/*Index  Cluster AddressClientInformation*/


CREATE CLUSTERED INDEX [ClusteredIndex-20220611-153541] ON [Acceso].[AddressClientInformation]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*Index cluter [installments_payments]*/


CREATE CLUSTERED INDEX [ClusteredIndex-20220611-164328] ON [Saldos].[installments_payments]
(
	[SK_ID_PREV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*Index Cluerster POS_CASH_balance*/


CREATE CLUSTERED INDEX [ClusteredIndex-20220611-164503] ON [Saldos].[POS_CASH_balance]
(
	[SK_ID_PREV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)









