
/*No cluster index [credit_card_balance]*/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-173153] ON [Saldos].[credit_card_balance]
(
	[SK_ID_PREV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-173215] ON [Saldos].[credit_card_balance]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*No cluster index [bureau] */


CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-173400] ON [Creditos].[bureau]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*No cluster index [POS_CASH_balance] */

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-173654] ON [Saldos].[POS_CASH_balance]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)



/*No cluster index installments_payments*/


CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-174117] ON [Saldos].[installments_payments]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)


/*No cluster index [previous_application]*/

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220611-182116] ON [Saldos].[previous_application]
(
	[SK_ID_CURR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)








