USE [ProyectoBasesDatos2]
GO

DROP PROCEDURE SPInsertAMT_BALANCE_DETAILS;
CREATE PROCEDURE SPInsertAMT_BALANCE_DETAILS 
			@ID_CCB VARCHAR
           ,@BALANCE VARCHAR
           ,@CREDIT_LIMIT_ACTUAL VARCHAR
           ,@DRAWINGS_ATM_CURRENT VARCHAR
           ,@DRAWINGS_CURRENT VARCHAR
           ,@DRAWINGS_OTHER_CURRENT VARCHAR
           ,@DRAWINGS_POS_CURRENT VARCHAR
           ,@INST_MIN_REGULARITY VARCHAR
           ,@PAYMENT_CURRENT VARCHAR
           ,@PAYMENT_TOTAL_CURRENT VARCHAR
           ,@RECEIVABLE_PRINCIPAL VARCHAR
           ,@RECIVABLE VARCHAR
           ,@TOTAL_RECEIVABLE VARCHAR
AS
	BEGIN
	INSERT INTO [Saldos].[AMT_BALANCE_DETAILS]
           ([ID_CCB]
           ,[BALANCE]
           ,[CREDIT_LIMIT_ACTUAL]
           ,[DRAWINGS_ATM_CURRENT]
           ,[DRAWINGS_CURRENT]
           ,[DRAWINGS_OTHER_CURRENT]
           ,[DRAWINGS_POS_CURRENT]
           ,[INST_MIN_REGULARITY]
           ,[PAYMENT_CURRENT]
           ,[PAYMENT_TOTAL_CURRENT]
           ,[RECEIVABLE_PRINCIPAL]
           ,[RECIVABLE]
           ,[TOTAL_RECEIVABLE])
     VALUES
           (@ID_CCB
           ,@BALANCE
           ,@CREDIT_LIMIT_ACTUAL
           ,@DRAWINGS_ATM_CURRENT
           ,@DRAWINGS_CURRENT
           ,@DRAWINGS_OTHER_CURRENT
           ,@DRAWINGS_POS_CURRENT
           ,@INST_MIN_REGULARITY
           ,@PAYMENT_CURRENT
           ,@PAYMENT_TOTAL_CURRENT
           ,@RECEIVABLE_PRINCIPAL
           ,@RECIVABLE
           ,@TOTAL_RECEIVABLE)


	END
GO



