USE [ProyectoBasesDatos2]
GO


DROP PROCEDURE SPInsertarPreviousApplication;
CREATE PROCEDURE SPInsertarPreviousApplication @SK_ID_PREV varchar
, @SK_ID_CURR varchar
, @NAME_CONTRACT_TYPE varchar
, @WEEKDAY_APPR_PROCESS_START varchar
, @HOUR_APPR_PROCESS_START varchar
, @FLAG_LAST_APPL_PER_CONTRACT varchar
, @NFLAG_LAST_APPL_IN_DAY varchar
, @RATE_DOWN_PAYMENT varchar
, @RATE_INTEREST_PRIMARY varchar
, @RATE_INTEREST_PRIVILEGED varchar
, @NAME_CASH_LOAN_PURPOSE varchar
, @NAME_CONTRACT_STATUS varchar
, @DAYS_DECISION varchar
, @NAME_PAYMENT_TYPE varchar
, @CODE_REJECT_REASON varchar
, @NAME_TYPE_SUITE varchar
, @NAME_CLIENT_TYPE varchar
, @NAME_GOODS_CATEGORY varchar
, @NAME_PORTFOLIO varchar
, @NAME_PRODUCT_TYPE varchar
, @CHANNEL_TYPE varchar
, @SELLERPLACE_AREA varchar
, @NAME_SELLER_INDUSTRY varchar
, @CNT_PAYMENT varchar
, @NAME_YIELD_GROUP varchar
, @PRODUCT_COMBINATION varchar
, @DAYS_FIRST_DRAWING varchar
, @DAYS_FIRST_DUE varchar
, @DAYS_LAST_DUE_1ST_VERSION varchar
, @DAYS_LAST_DUE varchar
, @DAYS_TERMINATION varchar
, @NFLAG_INSURED_ON_APPROVAL varchar
AS
BEGIN

  INSERT INTO [Saldos].[previous_application] ([SK_ID_PREV]
  , [SK_ID_CURR]
  , [NAME_CONTRACT_TYPE]
  , [WEEKDAY_APPR_PROCESS_START]
  , [HOUR_APPR_PROCESS_START]
  , [FLAG_LAST_APPL_PER_CONTRACT]
  , [NFLAG_LAST_APPL_IN_DAY]
  , [RATE_DOWN_PAYMENT]
  , [RATE_INTEREST_PRIMARY]
  , [RATE_INTEREST_PRIVILEGED]
  , [NAME_CASH_LOAN_PURPOSE]
  , [NAME_CONTRACT_STATUS]
  , [DAYS_DECISION]
  , [NAME_PAYMENT_TYPE]
  , [CODE_REJECT_REASON]
  , [NAME_TYPE_SUITE]
  , [NAME_CLIENT_TYPE]
  , [NAME_GOODS_CATEGORY]
  , [NAME_PORTFOLIO]
  , [NAME_PRODUCT_TYPE]
  , [CHANNEL_TYPE]
  , [SELLERPLACE_AREA]
  , [NAME_SELLER_INDUSTRY]
  , [CNT_PAYMENT]
  , [NAME_YIELD_GROUP]
  , [PRODUCT_COMBINATION]
  , [DAYS_FIRST_DRAWING]
  , [DAYS_FIRST_DUE]
  , [DAYS_LAST_DUE_1ST_VERSION]
  , [DAYS_LAST_DUE]
  , [DAYS_TERMINATION]
  , [NFLAG_INSURED_ON_APPROVAL])

    VALUES (@SK_ID_PREV, @SK_ID_CURR, @NAME_CONTRACT_TYPE, 
	@WEEKDAY_APPR_PROCESS_START, @HOUR_APPR_PROCESS_START, 
	@FLAG_LAST_APPL_PER_CONTRACT, @NFLAG_LAST_APPL_IN_DAY,
	@RATE_DOWN_PAYMENT, @RATE_INTEREST_PRIMARY, @RATE_INTEREST_PRIVILEGED,
	@NAME_CASH_LOAN_PURPOSE, @NAME_CONTRACT_STATUS, @DAYS_DECISION, 
	@NAME_PAYMENT_TYPE, @CODE_REJECT_REASON, @NAME_TYPE_SUITE,
	@NAME_CLIENT_TYPE, @NAME_GOODS_CATEGORY, @NAME_PORTFOLIO, 
	@NAME_PRODUCT_TYPE, @CHANNEL_TYPE, @SELLERPLACE_AREA, 
	@NAME_SELLER_INDUSTRY, @CNT_PAYMENT, @NAME_YIELD_GROUP, 
	@PRODUCT_COMBINATION, @DAYS_FIRST_DRAWING, @DAYS_FIRST_DUE, 
	@DAYS_LAST_DUE_1ST_VERSION, @DAYS_LAST_DUE, @DAYS_TERMINATION, 
	@NFLAG_INSURED_ON_APPROVAL)

END
GO

