USE [ProyectoBasesDatos2]
GO
DROP PROCEDURE SPInsertInstallmentsPayments;
CREATE PROCEDURE SPInsertInstallmentsPayments @SK_ID_PREV varchar
, @SK_ID_CURR varchar
, @NUM_INSTALMENT_VERSION varchar
, @NUM_INSTALMENT_NUMBER varchar
, @DAYS_INSTALMENT varchar
, @DAYS_ENTRY_PAYMENT varchar
, @AMT_INSTALMENT varchar
, @AMT_PAYMENT varchar
AS
BEGIN
  INSERT INTO [Saldos].[installments_payments] ([SK_ID_PREV]
  , [SK_ID_CURR]
  , [NUM_INSTALMENT_VERSION]
  , [NUM_INSTALMENT_NUMBER]
  , [DAYS_INSTALMENT]
  , [DAYS_ENTRY_PAYMENT]
  , [AMT_INSTALMENT]
  , [AMT_PAYMENT])

    VALUES (@SK_ID_PREV, @SK_ID_CURR, @NUM_INSTALMENT_VERSION, 
	@NUM_INSTALMENT_NUMBER, @DAYS_INSTALMENT, @DAYS_ENTRY_PAYMENT, 
	@AMT_INSTALMENT, @AMT_PAYMENT)
END
GO