USE [ProyectoBasesDatos2]
GO

DROP PROCEDURE SPInsertClientApartmentsDetails;
CREATE PROCEDURE SPInsertClientApartmentsDetails 
			@SK_ID_CURR VARCHAR
           ,@APARTMENTS_AVG VARCHAR
           ,@BASEMENTAREA_AVG VARCHAR
           ,@YEARS_BEGINEXPLUATATION_AVG VARCHAR
           ,@YEARS_BUILD_AVG VARCHAR
           ,@COMMONAREA_AVG VARCHAR
           ,@ELEVATORS_AVG VARCHAR
           ,@ENTRANCES_AVG VARCHAR
           ,@FLOORSMAX_AVG VARCHAR
           ,@FLOORSMIN_AVG VARCHAR
           ,@LANDAREA_AVG VARCHAR
           ,@LIVINGAPARTMENTS_AVG VARCHAR
           ,@LIVINGAREA_AVG VARCHAR
           ,@NONLIVINGAPARTMENTS_AVG VARCHAR
           ,@NONLIVINGAREA_AVG VARCHAR
           ,@APARTMENTS_MODE VARCHAR
           ,@BASEMENTAREA_MODE VARCHAR
           ,@YEARS_BEGINEXPLUATATION_MODE VARCHAR
           ,@YEARS_BUILD_MODE VARCHAR
           ,@COMMONAREA_MODE VARCHAR
           ,@ELEVATORS_MODE VARCHAR
           ,@ENTRANCES_MODE VARCHAR
           ,@FLOORSMAX_MODE VARCHAR
           ,@FLOORSMIN_MODE VARCHAR
           ,@LANDAREA_MODE VARCHAR
           ,@LIVINGAPARTMENTS_MODE VARCHAR
           ,@LIVINGAREA_MODE VARCHAR
           ,@NONLIVINGAPARTMENTS_MODE VARCHAR
           ,@NONLIVINGAREA_MODE VARCHAR
           ,@APARTMENTS_MEDI VARCHAR
           ,@BASEMENTAREA_MEDI VARCHAR
           ,@YEARS_BEGINEXPLUATATION_MEDI VARCHAR
           ,@YEARS_BUILD_MEDI VARCHAR
           ,@COMMONAREA_MEDI VARCHAR
           ,@ELEVATORS_MEDI VARCHAR
           ,@ENTRANCES_MEDI VARCHAR
           ,@FLOORSMAX_MEDI VARCHAR
           ,@FLOORSMIN_MEDI VARCHAR
           ,@LANDAREA_MEDI VARCHAR
           ,@LIVINGAPARTMENTS_MEDI VARCHAR
           ,@LIVINGAREA_MEDI VARCHAR
           ,@NONLIVINGAPARTMENTS_MEDI VARCHAR
           ,@NONLIVINGAREA_MEDI VARCHAR
           ,@FONDKAPREMONT_MODE VARCHAR
           ,@HOUSETYPE_MODE VARCHAR
           ,@TOTALAREA_MODE VARCHAR
           ,@WALLSMATERIAL_MODE VARCHAR
           ,@EMERGENCYSTATE_MODE VARCHAR
AS
	BEGIN
	INSERT INTO [Acceso].[ClientApartmentsDetails]
           ([SK_ID_CURR]
           ,[APARTMENTS_AVG]
           ,[BASEMENTAREA_AVG]
           ,[YEARS_BEGINEXPLUATATION_AVG]
           ,[YEARS_BUILD_AVG]
           ,[COMMONAREA_AVG]
           ,[ELEVATORS_AVG]
           ,[ENTRANCES_AVG]
           ,[FLOORSMAX_AVG]
           ,[FLOORSMIN_AVG]
           ,[LANDAREA_AVG]
           ,[LIVINGAPARTMENTS_AVG]
           ,[LIVINGAREA_AVG]
           ,[NONLIVINGAPARTMENTS_AVG]
           ,[NONLIVINGAREA_AVG]
           ,[APARTMENTS_MODE]
           ,[BASEMENTAREA_MODE]
           ,[YEARS_BEGINEXPLUATATION_MODE]
           ,[YEARS_BUILD_MODE]
           ,[COMMONAREA_MODE]
           ,[ELEVATORS_MODE]
           ,[ENTRANCES_MODE]
           ,[FLOORSMAX_MODE]
           ,[FLOORSMIN_MODE]
           ,[LANDAREA_MODE]
           ,[LIVINGAPARTMENTS_MODE]
           ,[LIVINGAREA_MODE]
           ,[NONLIVINGAPARTMENTS_MODE]
           ,[NONLIVINGAREA_MODE]
           ,[APARTMENTS_MEDI]
           ,[BASEMENTAREA_MEDI]
           ,[YEARS_BEGINEXPLUATATION_MEDI]
           ,[YEARS_BUILD_MEDI]
           ,[COMMONAREA_MEDI]
           ,[ELEVATORS_MEDI]
           ,[ENTRANCES_MEDI]
           ,[FLOORSMAX_MEDI]
           ,[FLOORSMIN_MEDI]
           ,[LANDAREA_MEDI]
           ,[LIVINGAPARTMENTS_MEDI]
           ,[LIVINGAREA_MEDI]
           ,[NONLIVINGAPARTMENTS_MEDI]
           ,[NONLIVINGAREA_MEDI]
           ,[FONDKAPREMONT_MODE]
           ,[HOUSETYPE_MODE]
           ,[TOTALAREA_MODE]
           ,[WALLSMATERIAL_MODE]
           ,[EMERGENCYSTATE_MODE])
     VALUES
           (@SK_ID_CURR
           ,@APARTMENTS_AVG
           ,@BASEMENTAREA_AVG
           ,@YEARS_BEGINEXPLUATATION_AVG
           ,@YEARS_BUILD_AVG
           ,@COMMONAREA_AVG
           ,@ELEVATORS_AVG
           ,@ENTRANCES_AVG
           ,@FLOORSMAX_AVG
           ,@FLOORSMIN_AVG
           ,@LANDAREA_AVG
           ,@LIVINGAPARTMENTS_AVG
           ,@LIVINGAREA_AVG
           ,@NONLIVINGAPARTMENTS_AVG
           ,@NONLIVINGAREA_AVG
           ,@APARTMENTS_MODE
           ,@BASEMENTAREA_MODE
           ,@YEARS_BEGINEXPLUATATION_MODE
           ,@YEARS_BUILD_MODE
           ,@COMMONAREA_MODE
           ,@ELEVATORS_MODE
           ,@ENTRANCES_MODE
           ,@FLOORSMAX_MODE
           ,@FLOORSMIN_MODE
           ,@LANDAREA_MODE
           ,@LIVINGAPARTMENTS_MODE
           ,@LIVINGAREA_MODE
           ,@NONLIVINGAPARTMENTS_MODE
           ,@NONLIVINGAREA_MODE
           ,@APARTMENTS_MEDI
           ,@BASEMENTAREA_MEDI
           ,@YEARS_BEGINEXPLUATATION_MEDI
           ,@YEARS_BUILD_MEDI
           ,@COMMONAREA_MEDI
           ,@ELEVATORS_MEDI
           ,@ENTRANCES_MEDI
           ,@FLOORSMAX_MEDI
           ,@FLOORSMIN_MEDI
           ,@LANDAREA_MEDI
           ,@LIVINGAPARTMENTS_MEDI
           ,@LIVINGAREA_MEDI
           ,@NONLIVINGAPARTMENTS_MEDI
           ,@NONLIVINGAREA_MEDI
           ,@FONDKAPREMONT_MODE
           ,@HOUSETYPE_MODE
           ,@TOTALAREA_MODE
           ,@WALLSMATERIAL_MODE
           ,@EMERGENCYSTATE_MODE)

	END
GO



