USE [ProyectoBasesDatos2]
GO

DROP PROCEDURE SPInsertCNTBalanceDetails;
CREATE PROCEDURE SPInsertCNTBalanceDetails @ID_CCB INT
, @DRAWINGS_ATM_CURRENT varchar(50)
, @DRAWINGS_CURRENT varchar(50)
, @DRAWINGS_OTHER_CURRENT varchar(50)
, @DRAWINGS_POS_CURRENT varchar(50)
, @INSTALMENT_MATURE_CUM varchar(50)
AS
BEGIN
  INSERT INTO [Saldos].[CNT_BALANCE_DETAILS] ([ID_CCB]
  , [DRAWINGS_ATM_CURRENT]
  , [DRAWINGS_CURRENT]
  , [DRAWINGS_OTHER_CURRENT]
  , [DRAWINGS_POS_CURRENT]
  , [INSTALMENT_MATURE_CUM])

    VALUES (@ID_CCB, @DRAWINGS_ATM_CURRENT, @DRAWINGS_CURRENT, 
	@DRAWINGS_OTHER_CURRENT, @DRAWINGS_POS_CURRENT, 
	@INSTALMENT_MATURE_CUM)

END
GO
