USE [ProyectoBasesDatos2]
GO
DROP PROCEDURE SPInsertInstallmentsPayments;
CREATE PROCEDURE SPInsertInstallmentsPayments 
  @SK_ID_PREV INT
, @SK_ID_CURR INT
, @NUM_INSTALMENT_VERSION varchar(50)
, @NUM_INSTALMENT_NUMBER varchar(50)
, @DAYS_INSTALMENT varchar(50)
, @DAYS_ENTRY_PAYMENT varchar(50)
, @AMT_INSTALMENT varchar(50)
, @AMT_PAYMENT varchar(50)
AS
BEGIN
  INSERT INTO [Saldos].[installments_payments] ([SK_ID_PREV]
  , [SK_ID_CURR]
  , [NUM_INSTALMENT_VERSION]
  , [NUM_INSTALMENT_NUMBER]
  , [DAYS_INSTALMENT]
  , [DAYS_ENTRY_PAYMENT]
  , [AMT_INSTALMENT]
  , [AMT_PAYMENT])

    VALUES (@SK_ID_PREV, @SK_ID_CURR, @NUM_INSTALMENT_VERSION, 
	@NUM_INSTALMENT_NUMBER, @DAYS_INSTALMENT, @DAYS_ENTRY_PAYMENT, 
	@AMT_INSTALMENT, @AMT_PAYMENT)
END
GO