USE [ProyectoBasesDatos2]
GO

DROP PROCEDURE SPInsertCNTBalanceDetails;
CREATE PROCEDURE SPInsertCNTBalanceDetails @ID_CCB varchar
, @DRAWINGS_ATM_CURRENT varchar
, @DRAWINGS_CURRENT varchar
, @DRAWINGS_OTHER_CURRENT varchar
, @DRAWINGS_POS_CURRENT varchar
, @INSTALMENT_MATURE_CUM varchar
AS
BEGIN
  INSERT INTO [Saldos].[CNT_BALANCE_DETAILS] ([ID_CCB]
  , [DRAWINGS_ATM_CURRENT]
  , [DRAWINGS_CURRENT]
  , [DRAWINGS_OTHER_CURRENT]
  , [DRAWINGS_POS_CURRENT]
  , [INSTALMENT_MATURE_CUM])

    VALUES (@ID_CCB, @DRAWINGS_ATM_CURRENT, @DRAWINGS_CURRENT, 
	@DRAWINGS_OTHER_CURRENT, @DRAWINGS_POS_CURRENT, 
	@INSTALMENT_MATURE_CUM)

END
GO
