USE [ProyectoBasesDatos2]
GO

DROP PROCEDURE SPInsertFlagsProvidedInfo;
CREATE PROCEDURE SPInsertFlagsProvidedInfo 
@SK_ID_CURR INT
, @FLAG_OWN_CAR varchar(50)
, @FLAG_OWN_REALTY varchar(50)
, @FLAG_MOBIL varchar(50)
, @FLAG_EMP_PHONE varchar(50)
, @FLAG_WORK_PHONE varchar(50)
, @FLAG_CONT_MOBILE varchar(50)
, @FLAG_PHONE varchar(50)
, @FLAG_EMAIL varchar(50)
AS
BEGIN
  INSERT INTO [Acceso].[FlagsProvidedInformation] ([SK_ID_CURR]
  , [FLAG_OWN_CAR]
  , [FLAG_OWN_REALTY]
  , [FLAG_MOBIL]
  , [FLAG_EMP_PHONE]
  , [FLAG_WORK_PHONE]
  , [FLAG_CONT_MOBILE]
  , [FLAG_PHONE]
  , [FLAG_EMAIL])

    VALUES (@SK_ID_CURR, @FLAG_OWN_CAR, @FLAG_OWN_REALTY, 
	@FLAG_MOBIL, @FLAG_EMP_PHONE, @FLAG_WORK_PHONE, 
	@FLAG_CONT_MOBILE, @FLAG_PHONE, @FLAG_EMAIL)

END
GO