USE [ProyectoBasesDatos2]
GO


DROP PROCEDURE SPInsertarPreviousApplication;
CREATE PROCEDURE SPInsertarPreviousApplication 
  @SK_ID_PREV INT
, @SK_ID_CURR INT
, @NAME_CONTRACT_TYPE varchar(50)
, @WEEKDAY_APPR_PROCESS_START varchar(50)
, @HOUR_APPR_PROCESS_START varchar(50)
, @FLAG_LAST_APPL_PER_CONTRACT varchar(50)
, @NFLAG_LAST_APPL_IN_DAY varchar(50)
, @RATE_DOWN_PAYMENT varchar(50)
, @RATE_INTEREST_PRIMARY varchar(50)
, @RATE_INTEREST_PRIVILEGED varchar(50)
, @NAME_CASH_LOAN_PURPOSE varchar(50)
, @NAME_CONTRACT_STATUS varchar(50)
, @DAYS_DECISION varchar(50)
, @NAME_PAYMENT_TYPE varchar(50)
, @CODE_REJECT_REASON varchar(50)
, @NAME_TYPE_SUITE varchar(50)
, @NAME_CLIENT_TYPE varchar(50)
, @NAME_GOODS_CATEGORY varchar(50)
, @NAME_PORTFOLIO varchar(50)
, @NAME_PRODUCT_TYPE varchar(50)
, @CHANNEL_TYPE varchar(50)
, @SELLERPLACE_AREA varchar(50)
, @NAME_SELLER_INDUSTRY varchar(50)
, @CNT_PAYMENT varchar(50)
, @NAME_YIELD_GROUP varchar(50)
, @PRODUCT_COMBINATION varchar(50)
, @DAYS_FIRST_DRAWING varchar(50)
, @DAYS_FIRST_DUE varchar(50)
, @DAYS_LAST_DUE_1ST_VERSION varchar(50)
, @DAYS_LAST_DUE varchar(50)
, @DAYS_TERMINATION varchar(50)
, @NFLAG_INSURED_ON_APPROVAL varchar(50)
AS
BEGIN

  INSERT INTO [Saldos].[previous_application] ([SK_ID_PREV]
  , [SK_ID_CURR]
  , [NAME_CONTRACT_TYPE]
  , [WEEKDAY_APPR_PROCESS_START]
  , [HOUR_APPR_PROCESS_START]
  , [FLAG_LAST_APPL_PER_CONTRACT]
  , [NFLAG_LAST_APPL_IN_DAY]
  , [RATE_DOWN_PAYMENT]
  , [RATE_INTEREST_PRIMARY]
  , [RATE_INTEREST_PRIVILEGED]
  , [NAME_CASH_LOAN_PURPOSE]
  , [NAME_CONTRACT_STATUS]
  , [DAYS_DECISION]
  , [NAME_PAYMENT_TYPE]
  , [CODE_REJECT_REASON]
  , [NAME_TYPE_SUITE]
  , [NAME_CLIENT_TYPE]
  , [NAME_GOODS_CATEGORY]
  , [NAME_PORTFOLIO]
  , [NAME_PRODUCT_TYPE]
  , [CHANNEL_TYPE]
  , [SELLERPLACE_AREA]
  , [NAME_SELLER_INDUSTRY]
  , [CNT_PAYMENT]
  , [NAME_YIELD_GROUP]
  , [PRODUCT_COMBINATION]
  , [DAYS_FIRST_DRAWING]
  , [DAYS_FIRST_DUE]
  , [DAYS_LAST_DUE_1ST_VERSION]
  , [DAYS_LAST_DUE]
  , [DAYS_TERMINATION]
  , [NFLAG_INSURED_ON_APPROVAL])

    VALUES (@SK_ID_PREV, @SK_ID_CURR, @NAME_CONTRACT_TYPE, 
	@WEEKDAY_APPR_PROCESS_START, @HOUR_APPR_PROCESS_START, 
	@FLAG_LAST_APPL_PER_CONTRACT, @NFLAG_LAST_APPL_IN_DAY,
	@RATE_DOWN_PAYMENT, @RATE_INTEREST_PRIMARY, @RATE_INTEREST_PRIVILEGED,
	@NAME_CASH_LOAN_PURPOSE, @NAME_CONTRACT_STATUS, @DAYS_DECISION, 
	@NAME_PAYMENT_TYPE, @CODE_REJECT_REASON, @NAME_TYPE_SUITE,
	@NAME_CLIENT_TYPE, @NAME_GOODS_CATEGORY, @NAME_PORTFOLIO, 
	@NAME_PRODUCT_TYPE, @CHANNEL_TYPE, @SELLERPLACE_AREA, 
	@NAME_SELLER_INDUSTRY, @CNT_PAYMENT, @NAME_YIELD_GROUP, 
	@PRODUCT_COMBINATION, @DAYS_FIRST_DRAWING, @DAYS_FIRST_DUE, 
	@DAYS_LAST_DUE_1ST_VERSION, @DAYS_LAST_DUE, @DAYS_TERMINATION, 
	@NFLAG_INSURED_ON_APPROVAL)

END
GO

